/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as ExperiencesGoatCuddlesRouteImport } from './routes/experiences_.goat-cuddles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesGoatCuddlesRoute = ExperiencesGoatCuddlesRouteImport.update({
  id: '/experiences_/goat-cuddles',
  path: '/experiences/goat-cuddles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRoute
  '/experiences/goat-cuddles': typeof ExperiencesGoatCuddlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRoute
  '/experiences/goat-cuddles': typeof ExperiencesGoatCuddlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesRoute
  '/experiences_/goat-cuddles': typeof ExperiencesGoatCuddlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiences' | '/experiences/goat-cuddles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiences' | '/experiences/goat-cuddles'
  id: '__root__' | '/' | '/experiences' | '/experiences_/goat-cuddles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesRoute: typeof ExperiencesRoute
  ExperiencesGoatCuddlesRoute: typeof ExperiencesGoatCuddlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/goat-cuddles': {
      id: '/experiences_/goat-cuddles'
      path: '/experiences/goat-cuddles'
      fullPath: '/experiences/goat-cuddles'
      preLoaderRoute: typeof ExperiencesGoatCuddlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesRoute: ExperiencesRoute,
  ExperiencesGoatCuddlesRoute: ExperiencesGoatCuddlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
