/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdoptAnAnimalRouteImport } from './routes/adopt-an-animal'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GiftCardRouteImport } from './routes/gift-card'
import { Route as ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRouteImport } from './routes/experiences_.alpaca-experience-and-fibre-nesting-ball-workshop'
import { Route as ExperiencesAlpacaLunchPicnicRouteImport } from './routes/experiences_.alpaca-lunch-picnic'
import { Route as ExperiencesAlpacaSunsetPicnicRouteImport } from './routes/experiences_.alpaca-sunset-picnic'
import { Route as ExperiencesAlpacaWalksRouteImport } from './routes/experiences_.alpaca-walks'
import { Route as ExperiencesBabyGoatPlaytimeAndSnugglesRouteImport } from './routes/experiences_.baby-goat-playtime-and-snuggles'
import { Route as ExperiencesFarmGlampingRouteImport } from './routes/experiences_.farm-glamping'
import { Route as ExperiencesGoatCuddlesRouteImport } from './routes/experiences_.goat-cuddles'
import { Route as ExperiencesGoatRecessRouteImport } from './routes/experiences_.goat-recess'
import { Route as ExperiencesMiniHighlandCalfMeetAndGreetRouteImport } from './routes/experiences_.mini-highland-calf-meet-and-greet'
import { Route as ExperiencesMiniHighlandCowExperienceRouteImport } from './routes/experiences_.mini-highland-cow-experience'
import { Route as ExperiencesMiniatureDonkeyVisitsRouteImport } from './routes/experiences_.miniature-donkey-visits'
import { Route as ExperiencesPrivateMiniatureDonkeyLunchPicnicRouteImport } from './routes/experiences_.private-miniature-donkey-lunch-picnic'
import { Route as ExperiencesPrivateMiniatureDonkeySunsetPicnicRouteImport } from './routes/experiences_.private-miniature-donkey-sunset-picnic'
import { Route as ExperiencesTasteOfFarmLifeRouteImport } from './routes/experiences_.taste-of-farm-life'
import { Route as ExperiencesTasteOfFarmLifeFamilyFriendlyRouteImport } from './routes/experiences_.taste-of-farm-life-family-friendly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptAnAnimalRoute = AdoptAnAnimalRouteImport.update({
  id: '/adopt-an-animal',
  path: '/adopt-an-animal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardRoute = GiftCardRouteImport.update({
  id: '/gift-card',
  path: '/gift-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute =
  ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRouteImport.update({
    id: '/experiences_/alpaca-experience-and-fibre-nesting-ball-workshop',
    path: '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesAlpacaLunchPicnicRoute =
  ExperiencesAlpacaLunchPicnicRouteImport.update({
    id: '/experiences_/alpaca-lunch-picnic',
    path: '/experiences/alpaca-lunch-picnic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesAlpacaSunsetPicnicRoute =
  ExperiencesAlpacaSunsetPicnicRouteImport.update({
    id: '/experiences_/alpaca-sunset-picnic',
    path: '/experiences/alpaca-sunset-picnic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesAlpacaWalksRoute = ExperiencesAlpacaWalksRouteImport.update({
  id: '/experiences_/alpaca-walks',
  path: '/experiences/alpaca-walks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesBabyGoatPlaytimeAndSnugglesRoute =
  ExperiencesBabyGoatPlaytimeAndSnugglesRouteImport.update({
    id: '/experiences_/baby-goat-playtime-and-snuggles',
    path: '/experiences/baby-goat-playtime-and-snuggles',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesFarmGlampingRoute = ExperiencesFarmGlampingRouteImport.update({
  id: '/experiences_/farm-glamping',
  path: '/experiences/farm-glamping',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesGoatCuddlesRoute = ExperiencesGoatCuddlesRouteImport.update({
  id: '/experiences_/goat-cuddles',
  path: '/experiences/goat-cuddles',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesGoatRecessRoute = ExperiencesGoatRecessRouteImport.update({
  id: '/experiences_/goat-recess',
  path: '/experiences/goat-recess',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesMiniHighlandCalfMeetAndGreetRoute =
  ExperiencesMiniHighlandCalfMeetAndGreetRouteImport.update({
    id: '/experiences_/mini-highland-calf-meet-and-greet',
    path: '/experiences/mini-highland-calf-meet-and-greet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesMiniHighlandCowExperienceRoute =
  ExperiencesMiniHighlandCowExperienceRouteImport.update({
    id: '/experiences_/mini-highland-cow-experience',
    path: '/experiences/mini-highland-cow-experience',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesMiniatureDonkeyVisitsRoute =
  ExperiencesMiniatureDonkeyVisitsRouteImport.update({
    id: '/experiences_/miniature-donkey-visits',
    path: '/experiences/miniature-donkey-visits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute =
  ExperiencesPrivateMiniatureDonkeyLunchPicnicRouteImport.update({
    id: '/experiences_/private-miniature-donkey-lunch-picnic',
    path: '/experiences/private-miniature-donkey-lunch-picnic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute =
  ExperiencesPrivateMiniatureDonkeySunsetPicnicRouteImport.update({
    id: '/experiences_/private-miniature-donkey-sunset-picnic',
    path: '/experiences/private-miniature-donkey-sunset-picnic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesTasteOfFarmLifeRoute =
  ExperiencesTasteOfFarmLifeRouteImport.update({
    id: '/experiences_/taste-of-farm-life',
    path: '/experiences/taste-of-farm-life',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesTasteOfFarmLifeFamilyFriendlyRoute =
  ExperiencesTasteOfFarmLifeFamilyFriendlyRouteImport.update({
    id: '/experiences_/taste-of-farm-life-family-friendly',
    path: '/experiences/taste-of-farm-life-family-friendly',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adopt-an-animal': typeof AdoptAnAnimalRoute
  '/experiences': typeof ExperiencesRoute
  '/gift-card': typeof GiftCardRoute
  '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop': typeof ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute
  '/experiences/alpaca-lunch-picnic': typeof ExperiencesAlpacaLunchPicnicRoute
  '/experiences/alpaca-sunset-picnic': typeof ExperiencesAlpacaSunsetPicnicRoute
  '/experiences/alpaca-walks': typeof ExperiencesAlpacaWalksRoute
  '/experiences/baby-goat-playtime-and-snuggles': typeof ExperiencesBabyGoatPlaytimeAndSnugglesRoute
  '/experiences/farm-glamping': typeof ExperiencesFarmGlampingRoute
  '/experiences/goat-cuddles': typeof ExperiencesGoatCuddlesRoute
  '/experiences/goat-recess': typeof ExperiencesGoatRecessRoute
  '/experiences/mini-highland-calf-meet-and-greet': typeof ExperiencesMiniHighlandCalfMeetAndGreetRoute
  '/experiences/mini-highland-cow-experience': typeof ExperiencesMiniHighlandCowExperienceRoute
  '/experiences/miniature-donkey-visits': typeof ExperiencesMiniatureDonkeyVisitsRoute
  '/experiences/private-miniature-donkey-lunch-picnic': typeof ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute
  '/experiences/private-miniature-donkey-sunset-picnic': typeof ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute
  '/experiences/taste-of-farm-life': typeof ExperiencesTasteOfFarmLifeRoute
  '/experiences/taste-of-farm-life-family-friendly': typeof ExperiencesTasteOfFarmLifeFamilyFriendlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adopt-an-animal': typeof AdoptAnAnimalRoute
  '/experiences': typeof ExperiencesRoute
  '/gift-card': typeof GiftCardRoute
  '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop': typeof ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute
  '/experiences/alpaca-lunch-picnic': typeof ExperiencesAlpacaLunchPicnicRoute
  '/experiences/alpaca-sunset-picnic': typeof ExperiencesAlpacaSunsetPicnicRoute
  '/experiences/alpaca-walks': typeof ExperiencesAlpacaWalksRoute
  '/experiences/baby-goat-playtime-and-snuggles': typeof ExperiencesBabyGoatPlaytimeAndSnugglesRoute
  '/experiences/farm-glamping': typeof ExperiencesFarmGlampingRoute
  '/experiences/goat-cuddles': typeof ExperiencesGoatCuddlesRoute
  '/experiences/goat-recess': typeof ExperiencesGoatRecessRoute
  '/experiences/mini-highland-calf-meet-and-greet': typeof ExperiencesMiniHighlandCalfMeetAndGreetRoute
  '/experiences/mini-highland-cow-experience': typeof ExperiencesMiniHighlandCowExperienceRoute
  '/experiences/miniature-donkey-visits': typeof ExperiencesMiniatureDonkeyVisitsRoute
  '/experiences/private-miniature-donkey-lunch-picnic': typeof ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute
  '/experiences/private-miniature-donkey-sunset-picnic': typeof ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute
  '/experiences/taste-of-farm-life': typeof ExperiencesTasteOfFarmLifeRoute
  '/experiences/taste-of-farm-life-family-friendly': typeof ExperiencesTasteOfFarmLifeFamilyFriendlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adopt-an-animal': typeof AdoptAnAnimalRoute
  '/experiences': typeof ExperiencesRoute
  '/gift-card': typeof GiftCardRoute
  '/experiences_/alpaca-experience-and-fibre-nesting-ball-workshop': typeof ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute
  '/experiences_/alpaca-lunch-picnic': typeof ExperiencesAlpacaLunchPicnicRoute
  '/experiences_/alpaca-sunset-picnic': typeof ExperiencesAlpacaSunsetPicnicRoute
  '/experiences_/alpaca-walks': typeof ExperiencesAlpacaWalksRoute
  '/experiences_/baby-goat-playtime-and-snuggles': typeof ExperiencesBabyGoatPlaytimeAndSnugglesRoute
  '/experiences_/farm-glamping': typeof ExperiencesFarmGlampingRoute
  '/experiences_/goat-cuddles': typeof ExperiencesGoatCuddlesRoute
  '/experiences_/goat-recess': typeof ExperiencesGoatRecessRoute
  '/experiences_/mini-highland-calf-meet-and-greet': typeof ExperiencesMiniHighlandCalfMeetAndGreetRoute
  '/experiences_/mini-highland-cow-experience': typeof ExperiencesMiniHighlandCowExperienceRoute
  '/experiences_/miniature-donkey-visits': typeof ExperiencesMiniatureDonkeyVisitsRoute
  '/experiences_/private-miniature-donkey-lunch-picnic': typeof ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute
  '/experiences_/private-miniature-donkey-sunset-picnic': typeof ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute
  '/experiences_/taste-of-farm-life': typeof ExperiencesTasteOfFarmLifeRoute
  '/experiences_/taste-of-farm-life-family-friendly': typeof ExperiencesTasteOfFarmLifeFamilyFriendlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adopt-an-animal'
    | '/experiences'
    | '/gift-card'
    | '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop'
    | '/experiences/alpaca-lunch-picnic'
    | '/experiences/alpaca-sunset-picnic'
    | '/experiences/alpaca-walks'
    | '/experiences/baby-goat-playtime-and-snuggles'
    | '/experiences/farm-glamping'
    | '/experiences/goat-cuddles'
    | '/experiences/goat-recess'
    | '/experiences/mini-highland-calf-meet-and-greet'
    | '/experiences/mini-highland-cow-experience'
    | '/experiences/miniature-donkey-visits'
    | '/experiences/private-miniature-donkey-lunch-picnic'
    | '/experiences/private-miniature-donkey-sunset-picnic'
    | '/experiences/taste-of-farm-life'
    | '/experiences/taste-of-farm-life-family-friendly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adopt-an-animal'
    | '/experiences'
    | '/gift-card'
    | '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop'
    | '/experiences/alpaca-lunch-picnic'
    | '/experiences/alpaca-sunset-picnic'
    | '/experiences/alpaca-walks'
    | '/experiences/baby-goat-playtime-and-snuggles'
    | '/experiences/farm-glamping'
    | '/experiences/goat-cuddles'
    | '/experiences/goat-recess'
    | '/experiences/mini-highland-calf-meet-and-greet'
    | '/experiences/mini-highland-cow-experience'
    | '/experiences/miniature-donkey-visits'
    | '/experiences/private-miniature-donkey-lunch-picnic'
    | '/experiences/private-miniature-donkey-sunset-picnic'
    | '/experiences/taste-of-farm-life'
    | '/experiences/taste-of-farm-life-family-friendly'
  id:
    | '__root__'
    | '/'
    | '/adopt-an-animal'
    | '/experiences'
    | '/gift-card'
    | '/experiences_/alpaca-experience-and-fibre-nesting-ball-workshop'
    | '/experiences_/alpaca-lunch-picnic'
    | '/experiences_/alpaca-sunset-picnic'
    | '/experiences_/alpaca-walks'
    | '/experiences_/baby-goat-playtime-and-snuggles'
    | '/experiences_/farm-glamping'
    | '/experiences_/goat-cuddles'
    | '/experiences_/goat-recess'
    | '/experiences_/mini-highland-calf-meet-and-greet'
    | '/experiences_/mini-highland-cow-experience'
    | '/experiences_/miniature-donkey-visits'
    | '/experiences_/private-miniature-donkey-lunch-picnic'
    | '/experiences_/private-miniature-donkey-sunset-picnic'
    | '/experiences_/taste-of-farm-life'
    | '/experiences_/taste-of-farm-life-family-friendly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptAnAnimalRoute: typeof AdoptAnAnimalRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GiftCardRoute: typeof GiftCardRoute
  ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute: typeof ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute
  ExperiencesAlpacaLunchPicnicRoute: typeof ExperiencesAlpacaLunchPicnicRoute
  ExperiencesAlpacaSunsetPicnicRoute: typeof ExperiencesAlpacaSunsetPicnicRoute
  ExperiencesAlpacaWalksRoute: typeof ExperiencesAlpacaWalksRoute
  ExperiencesBabyGoatPlaytimeAndSnugglesRoute: typeof ExperiencesBabyGoatPlaytimeAndSnugglesRoute
  ExperiencesFarmGlampingRoute: typeof ExperiencesFarmGlampingRoute
  ExperiencesGoatCuddlesRoute: typeof ExperiencesGoatCuddlesRoute
  ExperiencesGoatRecessRoute: typeof ExperiencesGoatRecessRoute
  ExperiencesMiniHighlandCalfMeetAndGreetRoute: typeof ExperiencesMiniHighlandCalfMeetAndGreetRoute
  ExperiencesMiniHighlandCowExperienceRoute: typeof ExperiencesMiniHighlandCowExperienceRoute
  ExperiencesMiniatureDonkeyVisitsRoute: typeof ExperiencesMiniatureDonkeyVisitsRoute
  ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute: typeof ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute
  ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute: typeof ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute
  ExperiencesTasteOfFarmLifeRoute: typeof ExperiencesTasteOfFarmLifeRoute
  ExperiencesTasteOfFarmLifeFamilyFriendlyRoute: typeof ExperiencesTasteOfFarmLifeFamilyFriendlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adopt-an-animal': {
      id: '/adopt-an-animal'
      path: '/adopt-an-animal'
      fullPath: '/adopt-an-animal'
      preLoaderRoute: typeof AdoptAnAnimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-card': {
      id: '/gift-card'
      path: '/gift-card'
      fullPath: '/gift-card'
      preLoaderRoute: typeof GiftCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/alpaca-experience-and-fibre-nesting-ball-workshop': {
      id: '/experiences_/alpaca-experience-and-fibre-nesting-ball-workshop'
      path: '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop'
      fullPath: '/experiences/alpaca-experience-and-fibre-nesting-ball-workshop'
      preLoaderRoute: typeof ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/alpaca-lunch-picnic': {
      id: '/experiences_/alpaca-lunch-picnic'
      path: '/experiences/alpaca-lunch-picnic'
      fullPath: '/experiences/alpaca-lunch-picnic'
      preLoaderRoute: typeof ExperiencesAlpacaLunchPicnicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/alpaca-sunset-picnic': {
      id: '/experiences_/alpaca-sunset-picnic'
      path: '/experiences/alpaca-sunset-picnic'
      fullPath: '/experiences/alpaca-sunset-picnic'
      preLoaderRoute: typeof ExperiencesAlpacaSunsetPicnicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/alpaca-walks': {
      id: '/experiences_/alpaca-walks'
      path: '/experiences/alpaca-walks'
      fullPath: '/experiences/alpaca-walks'
      preLoaderRoute: typeof ExperiencesAlpacaWalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/baby-goat-playtime-and-snuggles': {
      id: '/experiences_/baby-goat-playtime-and-snuggles'
      path: '/experiences/baby-goat-playtime-and-snuggles'
      fullPath: '/experiences/baby-goat-playtime-and-snuggles'
      preLoaderRoute: typeof ExperiencesBabyGoatPlaytimeAndSnugglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/farm-glamping': {
      id: '/experiences_/farm-glamping'
      path: '/experiences/farm-glamping'
      fullPath: '/experiences/farm-glamping'
      preLoaderRoute: typeof ExperiencesFarmGlampingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/goat-cuddles': {
      id: '/experiences_/goat-cuddles'
      path: '/experiences/goat-cuddles'
      fullPath: '/experiences/goat-cuddles'
      preLoaderRoute: typeof ExperiencesGoatCuddlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/goat-recess': {
      id: '/experiences_/goat-recess'
      path: '/experiences/goat-recess'
      fullPath: '/experiences/goat-recess'
      preLoaderRoute: typeof ExperiencesGoatRecessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/mini-highland-calf-meet-and-greet': {
      id: '/experiences_/mini-highland-calf-meet-and-greet'
      path: '/experiences/mini-highland-calf-meet-and-greet'
      fullPath: '/experiences/mini-highland-calf-meet-and-greet'
      preLoaderRoute: typeof ExperiencesMiniHighlandCalfMeetAndGreetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/mini-highland-cow-experience': {
      id: '/experiences_/mini-highland-cow-experience'
      path: '/experiences/mini-highland-cow-experience'
      fullPath: '/experiences/mini-highland-cow-experience'
      preLoaderRoute: typeof ExperiencesMiniHighlandCowExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/miniature-donkey-visits': {
      id: '/experiences_/miniature-donkey-visits'
      path: '/experiences/miniature-donkey-visits'
      fullPath: '/experiences/miniature-donkey-visits'
      preLoaderRoute: typeof ExperiencesMiniatureDonkeyVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/private-miniature-donkey-lunch-picnic': {
      id: '/experiences_/private-miniature-donkey-lunch-picnic'
      path: '/experiences/private-miniature-donkey-lunch-picnic'
      fullPath: '/experiences/private-miniature-donkey-lunch-picnic'
      preLoaderRoute: typeof ExperiencesPrivateMiniatureDonkeyLunchPicnicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/private-miniature-donkey-sunset-picnic': {
      id: '/experiences_/private-miniature-donkey-sunset-picnic'
      path: '/experiences/private-miniature-donkey-sunset-picnic'
      fullPath: '/experiences/private-miniature-donkey-sunset-picnic'
      preLoaderRoute: typeof ExperiencesPrivateMiniatureDonkeySunsetPicnicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/taste-of-farm-life': {
      id: '/experiences_/taste-of-farm-life'
      path: '/experiences/taste-of-farm-life'
      fullPath: '/experiences/taste-of-farm-life'
      preLoaderRoute: typeof ExperiencesTasteOfFarmLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences_/taste-of-farm-life-family-friendly': {
      id: '/experiences_/taste-of-farm-life-family-friendly'
      path: '/experiences/taste-of-farm-life-family-friendly'
      fullPath: '/experiences/taste-of-farm-life-family-friendly'
      preLoaderRoute: typeof ExperiencesTasteOfFarmLifeFamilyFriendlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptAnAnimalRoute: AdoptAnAnimalRoute,
  ExperiencesRoute: ExperiencesRoute,
  GiftCardRoute: GiftCardRoute,
  ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute:
    ExperiencesAlpacaExperienceAndFibreNestingBallWorkshopRoute,
  ExperiencesAlpacaLunchPicnicRoute: ExperiencesAlpacaLunchPicnicRoute,
  ExperiencesAlpacaSunsetPicnicRoute: ExperiencesAlpacaSunsetPicnicRoute,
  ExperiencesAlpacaWalksRoute: ExperiencesAlpacaWalksRoute,
  ExperiencesBabyGoatPlaytimeAndSnugglesRoute:
    ExperiencesBabyGoatPlaytimeAndSnugglesRoute,
  ExperiencesFarmGlampingRoute: ExperiencesFarmGlampingRoute,
  ExperiencesGoatCuddlesRoute: ExperiencesGoatCuddlesRoute,
  ExperiencesGoatRecessRoute: ExperiencesGoatRecessRoute,
  ExperiencesMiniHighlandCalfMeetAndGreetRoute:
    ExperiencesMiniHighlandCalfMeetAndGreetRoute,
  ExperiencesMiniHighlandCowExperienceRoute:
    ExperiencesMiniHighlandCowExperienceRoute,
  ExperiencesMiniatureDonkeyVisitsRoute: ExperiencesMiniatureDonkeyVisitsRoute,
  ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute:
    ExperiencesPrivateMiniatureDonkeyLunchPicnicRoute,
  ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute:
    ExperiencesPrivateMiniatureDonkeySunsetPicnicRoute,
  ExperiencesTasteOfFarmLifeRoute: ExperiencesTasteOfFarmLifeRoute,
  ExperiencesTasteOfFarmLifeFamilyFriendlyRoute:
    ExperiencesTasteOfFarmLifeFamilyFriendlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
